name: Mise en production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: zulu

    - name: Build le projet
      run: mvn clean package -DskipTests

    - name: Mettre les d√©pendences en cache
      uses: actions/cache@v4
      with:
        path: $MAVEN_OPTS
        key: librairies

    - name: Upload dans l'artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: helloworld-${{ vars.PROJECT_VERSION }}
        path: target/*.jar
      
