name: Génrérer JAR et déployer en prod

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=~dependances/lib/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: zulu

    - name: Build le projet
      run: mvn clean package -DskipTests

    - name: Mettre les dépendences en cache
      uses: actions/cache@v4
      with:
        path: $MAVEN_OPTS
        key: librairies

    - name: Upload dans l'artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: helloworld-${{ vars.PROJECT_VERSION }}
        path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - name: Récupérer le cache Maven
        uses: actions/cache@v4
        with:
          path: $MAVEN_OPTS
          key: librairies

      - uses: actions/checkout@main

      - name: Lancer les tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Télécharger le code compilé
        uses: actions/download-artifact@v4
        with:
          name: helloworld-${{ vars.PROJECT_VERSION }}

      - name: Déployer en production
        run: echo "Déploiement en production du JAR helloworld-${{ vars.PROJECT_VERSION }}.jar"
